### ISSUE TITLE
Create a v1 tag or something similar

### ISSUE THREAD

**Issue by s0undt3ch** [check-run-reporter/action#1]
I seem to be unable to use this action because it hasn't been tagged yet. Using the master branch is not an option.
```
Download action repository 'check-run-reporter/actions@master'
##[warning]Failed to download action 'https://api.github.com/repos/check-run-reporter/actions/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
```

**Comment by ianwremmel** [comment]
yep, it's still a work in progress, but hopefully it'll be usable in the next few weeks.

**Comment by ianwremmel** [comment]
in the short term, the curl option will work, but this is definitely highish on the priority list.

**Comment by ianwremmel** [comment]
Hi @s0undt3ch. Just wanted to let you know that `v1.0.0` has been tagged. There's a bit of an oddity around the `root` parameter that I'm now sure how to improve beyond the documentation that's in the readme. Please give it a shot and open more issues if you have any trouble.
